#![allow(non_camel_case_types)]

use std::collections::HashMap;
use std::ptr;
use std::rc::Rc;
use std::sync::Mutex;
use std::thread;
use std::time::{Duration, Instant};

use std::fs::metadata;
use std::os::unix::fs::MetadataExt;

use redbpf::{Map, Module, VoidPtr};

use grains::*;

include!(concat!(env!("OUT_DIR"), "/file.rs"));

type ino_t = u64;

const ACTION_IGNORE: u8 = 0;
const ACTION_RECORD: u8 = 1;

fn find_map_by_name<'a>(module: &'a mut Module, needle: &str) -> (usize, &'a mut Map) {
    module
        .maps
        .iter_mut()
        .enumerate()
        .find(|(i, v)| v.name == needle)
        .unwrap()
}

pub struct Files {
    files: Mutex<HashMap<ino_t, FileAccess>>,
    actionlist: HashMap<String, String>,
    backends: Vec<BackendHandler>,
    volumes: Option<Map>,
}

#[derive(Debug)]
pub struct FileAccess {
    pub id: u64,
    pub process: String,
    pub path: String,
    pub ino: ino_t,
}

impl Files {
    pub fn new() -> Files {
        Files {
            files: Mutex::new(HashMap::new()),
            actionlist: HashMap::new(),
            backends: vec![],
            volumes: None,
        }
    }
}

impl EBPFGrain<'static> for Files {
    fn loaded(&mut self, module: &mut Module) {
        let (volidx, _) = find_map_by_name(module, "volumes");

        {
            let (_, actionlist) = find_map_by_name(module, "actionlist");

            let mut record = _data_action {
                action: ACTION_RECORD,
            };
            let mut ino = metadata("/").unwrap().ino();
            actionlist.set(
                &mut ino as *mut ino_t as VoidPtr,
                &mut record as *mut _data_action as VoidPtr,
            );
        }

        let mut volumes = module.maps.swap_remove(volidx);
        thread::spawn(|| loop {
            thread::sleep(Duration::from_secs(5));

            for mut k in volumes.iter::<ino_t>() {
                let ino = Rc::get_mut(&mut k).unwrap();
                println!("{:?}", self.files.get_mut().unwrap().get_mut(&ino).unwrap());

                let ptr = ino as *mut ino_t as VoidPtr;

                volumes.delete(ptr);
            }
        });
    }

    fn attached(&mut self, backends: &[BackendHandler]) {
        self.backends.extend_from_slice(backends);
    }

    fn code() -> &'static [u8] {
        include_bytes!(concat!(env!("OUT_DIR"), "/file.elf"))
    }

    fn get_handler(&self, id: &str) -> EventCallback {
        Box::new(move |raw| {
            let file = FileAccess::from(_data_file::from(raw));
            self.files
                .get_mut()
                .unwrap()
                .entry(file.ino)
                .or_insert(file);

            // Not a goal to generate an event at this stage.
            // Events will be generated by the background thread for this grain.
            None
        })
    }
}

impl From<_data_file> for FileAccess {
    fn from(data: _data_file) -> FileAccess {
        let ino = data.path[0].ino;
        let path_segments = data.path.to_vec();
        path_segments.reverse();
        let path = path_segments
            .iter()
            .map(|s| to_string(unsafe { &*(&s.name as *const [i8] as *const [u8]) }))
            .collect::<Vec<String>>()
            .join("/");

        FileAccess {
            id: data.id,
            process: to_string(unsafe { &*(&data.comm as *const [i8] as *const [u8]) }),
            path,
            ino,
        }
    }
}
