FROM quay.io/redsift/ingraind-build:latest AS build

ADD . /build/
RUN cargo build --release

FROM debian:stable

RUN apt update && apt install -y libssl1.1 ca-certificates

COPY --from=build /usr/lib/x86_64-linux-gnu/libbpf.so* /usr/lib/
COPY --from=build /build/target/release/ingraind /bin

CMD /bin/ingraind
